/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jLogin.java
 *
 * Created on 23-oct-2013, 8:49:53
 */

package Login;

import Menu.Menu1;

import Splash.InicioAplicacion;
import Usuario.Usuario;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class Login extends javax.swing.JFrame {
     private InicioAplicacion splashFrame;
    /** Creates new form jLogin */
     public Login(InicioAplicacion splashFrame){
         this.splashFrame=splashFrame;
         initComponents();
         setProgress(0,"Cargando Componentes del sistema");
         setProgress(20,"Conectandose a la Base de Datos");
         setProgress(40,"Cargando modulos");
         setProgress(60,"Carga de modulos terminada");
         setProgress(80,"Cargando Interfaces");
             setProgress(90,"Interfaces Cargadas");
             setProgress(100,"Bienvenido al Sistema");
     }
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     private void setProgress(int percent, String informacion){
         splashFrame.getJLabel().setText(informacion);
         splashFrame.getJProgressBar().setValue(percent);

   try{
       Thread.sleep(1000);
   }catch (InterruptedException ex){
   JOptionPane.showMessageDialog(null,"No se pudo cargar la imagen");
   }
    };
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtP = new javax.swing.JPasswordField();
        txtU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login de Usuarios");
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 75, -1));
        getContentPane().add(txtP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));
        getContentPane().add(txtU, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 70, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 230));
        getContentPane().add(txtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{
     String usuario= txtU.getText();
     String pass = txtP.getText();
     String nivel =txtn.getText();
     Usuario e = new Usuario();
     e.setUsuario(txtU.getText());
     e.setPassword(txtP.getText());
     if(txtU.getText().length()>0 && txtP.getText().length()>0){
        if(validarUsuario(txtU.getText(),txtP.getText())){
          if(e.buscarUsuario()){
              txtn.setText(e.getNivel());
             if( txtn.getText().equals("administrador")){
               JOptionPane.showMessageDialog(null,"Bienvenido Administrador");
                  this.dispose();
                  Menu1 m = new Menu1();
                  m.setVisible(true);

              }else if(txtn.getText().equals("Empleado")){
                  JOptionPane.showMessageDialog(null,"Bienvenido Empleado");
                  this.dispose();
                 // Menu2 m2 = new Menu2();
                 // m2.setVisible(true);
              }else if(txtn.getText().equals("Contador")){
                  JOptionPane.showMessageDialog(null,"Bienvenido Contador");
                  this.dispose();
                 // Menu3 m3 = new Menu3();
                 // m3.setVisible(true);
              }
            }
         }
      }else{
         JOptionPane.showMessageDialog(null, "Error: Legajo o Contraseña incorrectos");
         txtU.setText("");    //limpiar campos
         txtP.setText("");        
         txtU.requestFocusInWindow();
      }
         }catch (Exception e){
            e.printStackTrace();
            System.out.println(e);
        }
    

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtP;
    private javax.swing.JTextField txtU;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
    boolean validarUsuario(String elUsr, String elPw)  throws IOException
    {
        try
        {

            Connection unaConexion  = DriverManager.getConnection ("jdbc:mysql://localhost/mydb","root", "");
            // Preparamos la consulta
            Statement instruccionSQL = unaConexion.createStatement();
            ResultSet resultadosConsulta = instruccionSQL.executeQuery ("SELECT Usuario , Password FROM mydb.Usuario where usuario='"+elUsr+"' AND password='"+ elPw+"'");

            if( resultadosConsulta.first() )        // si es valido el primer reg. hay una fila, tons el usuario y su pw existen
                return true;        //usuario validado correctamente
            else
                return false;        //usuario validado incorrectamente

        } catch (Exception e)
        {
            e.printStackTrace();
            return false;
        }

    }
}
