/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InicioAplicacion.java
 *
 * Created on 23-oct-2013, 15:38:23
 */

package Splash;

import Login.Login;
import com.sun.awt.AWTUtilities;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Marcos
 */
public class InicioAplicacion extends javax.swing.JFrame {
     private InicioAplicacion splashFrame=this;
    private Thread thread;
    /** Creates new form InicioAplicacion */
    public InicioAplicacion() {
        initComponents();
        AWTUtilities.setWindowOpacity(splashFrame, new Float(1));
        this.setLocationRelativeTo(null);
        startThread();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 11, -1, -1));
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 454, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 454, -1));
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 450, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    private void startThread() {
          Thread thread = new Thread(new Runnable() {

            public void run() {
                Login aplicationFrame = new Login(splashFrame);
                aplicationFrame.setLocationRelativeTo(null);
                aplicationFrame.setVisible(true);
                dispose();
            }
        });
        thread.start();
    }
    public JProgressBar getJProgressBar(){
        return progressBar;
    }
    public JLabel getJLabel(){
       return label;
    }

    private void Thread() {


    }

}
