/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ventana2.java
 *
 * Created on 26-oct-2013, 9:26:17
 */

package Docente;


import Asignatura.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class GrillaDocente extends javax.swing.JInternalFrame {
    private Asignatura Asignatura;
    private ListaAsignatura lista;
    DefaultTableModel model;
    /** Creates new form Ventana2 */
    public GrillaDocente() {
        Asignatura = new Asignatura();
        initComponents();
        mostrar();      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDocente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDocente1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        txtc = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "TELEFONO"
            }
        ));
        jtDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDocente);

        jtDocente1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "TELEFONO"
            }
        ));
        jtDocente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDocente1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtDocente1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcKeyTyped(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
       /* if(txtc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Modificar");
        }
        else{
            Asignatura c= new Asignatura();
            c.setAsignaturaId(Integer.parseInt(txtc.getText()));
            c.setCodigo(Integer.parseInt(txtCod.getText()));
            c.setNombre(txtNom.getText());
            String carga = (String) jComboCarga.getSelectedItem();
            int cargaSemanal =Integer.parseInt(carga);
            String ni = (String) jComboNivel.getSelectedItem();
            int nivel =Integer.parseInt(ni);
            c.setNivel(nivel);
            c.setCargaSemanal(cargaSemanal);
            c.modificar();
            JOptionPane.showMessageDialog(this, "La modificacion se realizo exitosamente");
            Asignatura = new Asignatura();
            mostrar();
            txtNom.setText("");
        
            txtc.setText("");
       
        }*/
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
       /* if(txtc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Eliminar");
        }
        else{
            Asignatura c = new Asignatura();
            c.setAsignaturaId(Integer.parseInt(txtc.getText()));
            c.setCodigo(Integer.parseInt(txtCod.getText()));
            c.setNombre(txtNom.getText());          
            c.bajas();
            JOptionPane.showMessageDialog(this, "La eliminacion se realizo exitosamente");
            Asignatura = new Asignatura();
            mostrar();
            txtNom.setText("");
            txtc.setText("");
 
        }*/
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void txtcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtcKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    NuevoDoc nd = new NuevoDoc();
    nd.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jtDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDocenteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDocenteMouseClicked

    private void jtDocente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDocente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDocente1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtDocente;
    private javax.swing.JTable jtDocente1;
    private javax.swing.JTextField txtc;
    // End of variables declaration//GEN-END:variables
  void mostrar() {
         try{
             ListaAsignatura lista = new ListaAsignatura(Asignatura.leer());
             DefaultTableModel info=new DefaultTableModel();
             info.addColumn("AsignaturaId");
             info.addColumn("Codigo");
             info.addColumn("Nombre");
             info.addColumn("Nivel");
             info.addColumn("CargaSemanal");
             for(int i=0; i<lista.getListaAsignatura().size();i++){
                Object[]fila=new Object[]{
                lista.getListaAsignatura().get(i).getAsignaturaId(),
                lista.getListaAsignatura().get(i).getCodigo(),    
                lista.getListaAsignatura().get(i).getNombre(),
                lista.getListaAsignatura().get(i).getNivel(),
                lista.getListaAsignatura().get(i).getCargaSemanal()
                };
                 info.addRow(fila);
            }
                 jtDocente.setModel(info);
        }catch(Exception a){
            a.printStackTrace();
        }

    }
 private void filtrar() {
     try{
        Asignatura c = new Asignatura();
        ListaAsignatura lista = new ListaAsignatura(Asignatura.filtrar());
        DefaultTableModel info=new DefaultTableModel();
        info.addColumn("AsignaturaId");
        info.addColumn("Codigo");
        info.addColumn("Nombre");
        info.addColumn("Nivel");
        info.addColumn("CargaSemanal");
        Asignatura.setAsignaturaId(Integer.parseInt(txtc.getText()));
        if(Asignatura.buscar())
            for(int i=0; i<lista.getListaAsignatura().size();i++){
                Object[]fila=new Object[]{
                lista.getListaAsignatura().get(i).getAsignaturaId(),
                lista.getListaAsignatura().get(i).getCodigo(),    
                lista.getListaAsignatura().get(i).getNombre(),
                lista.getListaAsignatura().get(i).getNivel(),
                lista.getListaAsignatura().get(i).getCargaSemanal()
        };
            info.addRow(fila);
          }
            jtDocente.setModel(info);
    }catch(Exception a){
      a.printStackTrace();
      }
  }
}
