/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ventana2.java
 *
 * Created on 26-oct-2013, 9:26:17
 */

package Docente;
import Abstracta.BD;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import Docente.BDDocente;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author Marcos
 */
public class NuevoDocente1 extends javax.swing.JInternalFrame {
    private Docente docente;
    private ListaDocentes lista;
    DefaultTableModel model;
    private int cont = 1;
    private NuevoDocente1 nd;
  
    public NuevoDocente1( ) {
          initComponents();       
          jtDocente.setVisible(true);
          actualizarBusqueda();
           txtCodigo.enable(false);
            txtrSoc.enable(false);
            txtdir.enable(false);
            
          }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtdir = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtrSoc = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnHabilitar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        cboParametroCli = new javax.swing.JComboBox();
        txtBuscarCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDocente = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane5.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel20.setText("Apellido");

        jLabel21.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel21.setText("Cargo");

        jLabel22.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel22.setText("Asignatura");

        txtdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdirActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel23.setText("Nombre");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtrSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrSocActionPerformed(evt);
            }
        });
        txtrSoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrSocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrSocKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel24.setText("Legajo");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnHabilitar.setText("Habilitar");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtrSoc, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtdir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eliminar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnHabilitar)
                    .addComponent(btnNuevo))
                .addGap(30, 30, 30))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtrSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHabilitar))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(jLabel21)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnCancelar)
                .addGap(33, 33, 33)
                .addComponent(btnBuscar)
                .addGap(43, 43, 43)
                .addComponent(btnModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnBuscar)
                    .addComponent(btnModificar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        jLabel25.setText("Opciones");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel25))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );

        jTabbedPane5.addTab("Nuevo Docente", jPanel7);

        jLabel32.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        jLabel32.setText("Docentes Registrados");

        cboParametroCli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Nombre" }));
        cboParametroCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboParametroCliActionPerformed(evt);
            }
        });

        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyReleased(evt);
            }
        });

        jLabel1.setText("BUSCAR :");

        jtDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "TELEFONO"
            }
        ));
        jtDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDocente);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboParametroCli, 0, 182, Short.MAX_VALUE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addGap(104, 104, 104))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboParametroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane5.addTab("Docente", jPanel17);

        getContentPane().add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 670, 400));
        jTabbedPane5.getAccessibleContext().setAccessibleName("Nuevo Docente");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrSocActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtrSocActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
       
}//GEN-LAST:event_txtCodigoActionPerformed

    private void txtdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdirActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtdirActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
         if(txtCodigo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Eliminar");
        }else{
        Docente d = new Docente  ();
        d.setLegajo(Integer.parseInt(txtCodigo.getText()));
        d.bajas();
        JOptionPane.showMessageDialog(this, "La eliminacion se realizo exitosamente");
        }
}//GEN-LAST:event_EliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
try {
             if(txtCodigo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Grabar");
            }else{
            int legajo =Integer.parseInt( txtCodigo.getText());
            String nombre = txtrSoc.getText();
            String apellido = txtdir.getText();
           // int cargoId = Integer.parseInt(txtcp.getText());
           // int asignaturaId =Integer.parseInt(txtmail.getText());
            Docente c= new Docente();
            c.setLegajo(legajo);
            c.setNombre(nombre);
            c.setApellido(apellido);
            c.setCargoId(cargoId);
            c.setAsignaturaId(asignaturaId);
            c.altas();
            JOptionPane.showMessageDialog(null,"Un nuevo Docente ha sido Registrado");
            txtCodigo.enable(false);
            txtrSoc.enable(false);
            txtdir.enable(false);
            txtcp.enable(false);
            txtmail.enable(false);
            txttel.enable(false);
            txtCodigo.setText("");
            txtrSoc.setText("");
            txtdir.setText("");
            txtcp.setText("");
            txtmail.setText("");
            txttel.setText("");
            }
        }catch( Exception ex){

            JOptionPane.showMessageDialog(null, "No se pudo cargar nuevo docente");

        }
        
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
 if(evt.getActionCommand().equals("boton"))
            txtCodigo.enable(false);
            txtrSoc.enable(true);
            txtdir.enable(true);
            txtcp.enable(true);
            txtmail.enable(true);
            txttel.enable(true);
              txtCodigo.setText("");
            txtrSoc.setText("");
            txtdir.setText("");
            txtcp.setText("");
            txtmail.setText("");
            txttel.setText("");
         cont++;
        
         txtCodigo.setText(""+cont++);
         repaint();
         limpiar();
         Docente d  = new Docente();
        try {
            Connection cn = BD.getConnection();
            Statement stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery("select max(legajo) from docente");
            while (rs.next()) {
                txtCodigo.setText(String.valueOf(rs.getInt(1)+1));
            }
            rs.close();
            stmt.close();
            cn.close();
        } catch (Exception error) {
            System.out.println(error);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
  if(txtCodigo.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Ingrese un Legajo para Buscar");
   }else{
        Docente d= new Docente();
        d.setLegajo(Integer.parseInt(txtCodigo.getText()));
        if(d.buscar()){
            txtrSoc.setText(d.getNombre());
            txtdir.setText(d.getApellido());
            txtcp.setText(""+d.getCargoId());
            txttel.setText(""+d.getAsignaturaId());
            txtrSoc.enable(false);
            txtdir.enable(false);
            txtmail.enable(false);
            txtcp.enable(false);
            txttel.enable(false);
        }else{
            JOptionPane.showMessageDialog(this, "No se encontraron coincidencias. Intentelo nuevamente");
             }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void btnhabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhabilitarActionPerformed
     
    }//GEN-LAST:event_btnhabilitarActionPerformed
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(txtCodigo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Modificar");
        }else{
        Docente d= new Docente();
        d.setLegajo(Integer.parseInt(txtCodigo.getText()));
        d.setNombre(txtrSoc.getText());
        d.setApellido(txtdir.getText());
        d.setAsignaturaId(Integer.parseInt(txttel.getText()));
        d.modificar();
        JOptionPane.showMessageDialog(this, "La modificacion se realizo exitosamente");
        txtCodigo.enable(false);
        txtrSoc.enable(false);
        txtdir.enable(false);
        txtcp.enable(false);
        txtmail.enable(false);
        txttel.enable(false);

        txtrSoc.setText("");
        txtdir.setText("");
        txtcp.setText("");
        txtmail.setText("");
        txttel.setText("");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased

    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
    char c = evt.getKeyChar();
    if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtrSocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrSocKeyReleased

    }//GEN-LAST:event_txtrSocKeyReleased

    private void txtrSocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrSocKeyTyped
       
    }//GEN-LAST:event_txtrSocKeyTyped

    private void cboParametroCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboParametroCliActionPerformed
    actualizarBusqueda();
}//GEN-LAST:event_cboParametroCliActionPerformed

    private void txtBuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyReleased
    actualizarBusqueda();
}//GEN-LAST:event_txtBuscarClienteKeyReleased

    private void jtDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDocenteMouseClicked
        // TODO add your handling code here:
      
}//GEN-LAST:event_jtDocenteMouseClicked

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
   txtCodigo.enable(true);
        txtrSoc.enable(true);
        txtdir.enable(true);
        txtcp.enable(true);
        txtmail.enable(true);
        txttel.enable(true);

        txtrSoc.setText("");
        txtdir.setText("");
        txtcp.setText("");
        txtmail.setText("");
        txttel.setText("");
    }//GEN-LAST:event_btnHabilitarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cboParametroCli;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jtDocente;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtrSoc;
    // End of variables declaration//GEN-END:variables


    private void mostrar() {
  try{

        Docente d = new Docente();
        ListaDocentes lista = new ListaDocentes(docente.leer());
        DefaultTableModel info=new DefaultTableModel();
        info.addColumn("Legajo");
        info.addColumn("Nombre");
        info.addColumn("Apellido");
        info.addColumn("CargoId");
        info.addColumn("AsignaturaId");
        
        for(int i=0; i<lista.getListaDocente().size();i++){

            Object[]fila=new Object[]{

                lista.getListaDocente().get(i).getLegajo(),
                lista.getListaDocente().get(i).getNombre(),
                lista.getListaDocente().get(i).getApellido(),
                lista.getListaDocente().get(i).getCargoId(),
                lista.getListaDocente().get(i).getAsignaturaId()
        };
        info.addRow(fila);
      }
     jtDocente.setModel(info);
  }catch(SQLException a){
      a.printStackTrace();
  }

    }

     private void filtrar() {
  try{

        Docente d = new Docente();
        ListaDocentes lista = new ListaDocentes(docente.filtrar());
        DefaultTableModel info=new DefaultTableModel();
        info.addColumn("Legajo");
        info.addColumn("Nombre");
        info.addColumn("Apellido");
        info.addColumn("CargoId");
        info.addColumn("AsignaturaId");
        docente.setLegajo(Integer.parseInt(txtBuscarCliente.getText()));
         
         if(docente.buscar())
        for(int i=0; i<lista.getListaDocente().size();i++){

            Object[]fila=new Object[]{
                
                lista.getListaDocente().get(i).getLegajo(),
                lista.getListaDocente().get(i).getNombre(),
                lista.getListaDocente().get(i).getApellido(),
                lista.getListaDocente().get(i).getCargoId(),
                lista.getListaDocente().get(i).getAsignaturaId()
             
        };
        info.addRow(fila);
      }
     jtDocente.setModel(info);
  }catch(SQLException a){
      a.printStackTrace();
  }
  }

    private void limpiar() {        
        txtrSoc.setText("");
        txtdir.setText("");
        txtcp.setText("");
        txtmail.setText("");
        txttel.setText("");
        }
    private void actualizarBusqueda() {
    ArrayList<Docente> result = null;
        if (String.valueOf(cboParametroCli.getSelectedItem()).equalsIgnoreCase("Codigo")) {
            result = BDDocente.listarDocentePorCodigo(txtBuscarCliente.getText());

        } else if (String.valueOf(cboParametroCli.getSelectedItem()).equalsIgnoreCase("Nombre")) {
            result = BDDocente.listarDocentePorNombre(txtBuscarCliente.getText());
        }
        recargarTable(result);
    }

    public void recargarTable(ArrayList<Docente> list) {
       try{ Object[][] datos = new Object[list.size()][5];
        int i = 0;
        for (Docente d : list) {
            datos[i][0] = d.getLegajo();
            datos[i][1] = d.getNombre();
            datos[i][2] = d.getApellido();
            datos[i][3] = d.getCargoId();
            datos[i][4] = d.getAsignaturaId();
            i++;
        }
        jtDocente.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "Legajo", "Nombre","Apellido","CargoId","Asignatura"
                }) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        }catch(Exception e){
            System.out.println(e);
        }
    }

}
