/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NuevoUsuario.java
 *
 * Created on 30-nov-2013, 20:19:08
 */

package Usuario;

import Empleado.Empleado;
import Empleado.GeneradorPassUser;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class NuevoUsuario extends javax.swing.JInternalFrame {

    /** Creates new form NuevoUsuario */
    public NuevoUsuario() {
        initComponents();
         txtL.enable(true);
         txtN.enable(false);
         txtA.enable(false);
         txtD.enable(false);
         txtDomicilio.enable(false);
         txttelefono.enable(false);
         txtcat.enable(false);

      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDom = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        txttelefono = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcat = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtU = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        txtnivel = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBorder(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 80, 10));
        jPanel3.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 170, 10));

        txtL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLActionPerformed(evt);
            }
        });
        jPanel3.add(txtL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 69, -1));

        jLabel1.setText("Legajo");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        jPanel3.add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 80, -1));
        jPanel3.add(txtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 108, -1));

        jLabel2.setText("Nombre");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel3.add(txtD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 108, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel3.setText("Apellido");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel7.setText("Dni");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 80, 20, -1));
        jPanel3.add(txtcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 80, 10));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(txtP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, -1));

        jLabel6.setText("Contraseña");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel4.add(txtU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, -1));

        jLabel5.setText("Usuario");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel4.setText("Nivel de Usuarios:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 250, 20));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Empleado", "Contador" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 142, 30));
        jPanel4.add(txtnivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 19, 10));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton11.setText("Generar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        generarcontraUser();
}//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Empleado e= new Empleado();
        e.setLegajo(Integer.parseInt(txtL.getText()));
        if(e.buscar()){
            txtN.setText(e.getNombre());
            txtA.setText(e.getApellido());
            txtD.setText(""+e.getDni());
 
            txtcat.setText(""+e.getIdcategoria());

            txtL.enable(false);
            txtN.enable(false);
            txtA.enable(false);
            txtD.enable(false);
            txtDomicilio.enable(false);
            txttelefono.enable(false);
            txtcat.enable(false);

       

        } else
            JOptionPane.showMessageDialog(this, "No se encontraron coincidencias. Intentelo nuevamente");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
            int legajo=Integer.parseInt(txtL.getText());
            int dni=Integer.parseInt(txtD.getText());
            String nombre=txtN.getText();
            String apellido= txtA.getText();
            int categoria = Integer.parseInt(txtcat.getText());
            String usuario= txtU.getText();
            String password= txtP.getText();
            int n = jComboBox.getSelectedIndex();
            if (n == 0){
                txtnivel.setText("Administrador");

            } else if(n == 1 ){
                txtnivel.setText("Empleado");
            }
            String nivel = txtnivel.getText();
            Usuario e= new Usuario();
             e.setLegajo(legajo);
             e.setUsuario(usuario);
             e.setPassword(password);
             e.setNivel(nivel);
             e.altas();
             JOptionPane.showMessageDialog(null,"Un nuevo Usuario ha sido Registrado");
             txtL.enable(false);
             txtD.enable(false);
             txtN.enable(false);
             txtA.enable(false);
             txtU.enable(false);
             txtP.enable(false);
       }catch( Exception ex){

        JOptionPane.showMessageDialog(null, "no se pudo cargar nuevo Usuario");
    
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtDom;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtL;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtU;
    private javax.swing.JTextField txtcat;
    private javax.swing.JTextField txtnivel;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
  public void  generarcontraUser(){
         GeneradorPassUser k = new GeneradorPassUser();
        String nom = txtN.getText();
        String ape = txtA.getText();

        if (nom.equals("") || ape.equals("") ) {
            JOptionPane.showMessageDialog(null, "Complete los campos nombre,apellido para generar el usuario", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            txtU.enable(false);

            txtU.setText(k.generarUser(nom, ape));
        }

        GeneradorPassUser q = new GeneradorPassUser();
        String dni = txtD.getText();
        String nom1 = txtN.getText();
        String ape1 = txtA.getText();

        if (dni.equals("") || ape1.equals("") || nom1.equals("")) {
            JOptionPane.showMessageDialog(null, "Complete los campos dni,apellido,nombre para generar el password", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            txtP.enable(false);
            txtP.setText(q.generarPass(nom1, dni, ape1));
        }
    }
}
